# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allergy',
            fields=[
                ('ALLERGY_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ALLERGY', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='doctorNotes',
            fields=[
                ('NOTE_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NOTES', models.TextField(max_length=255)),
                ('ALLERGY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.allergy')),
            ],
        ),
        migrations.CreateModel(
            name='emergencyContact',
            fields=[
                ('EC_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('F_NAME', models.CharField(max_length=20)),
                ('L_NAME', models.CharField(max_length=20)),
                ('PHONE_NUM', models.CharField(max_length=10)),
                ('RELATIONSHIP', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='main',
            fields=[
                ('USER_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('F_NAME', models.CharField(max_length=20)),
                ('L_NAME', models.CharField(max_length=20)),
                ('ADDRESS', models.CharField(max_length=200)),
                ('GENDER', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('BIRTHDAY', models.DateField()),
                ('EMAIL', models.CharField(max_length=30)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('HEALTHCARD_NUM', models.CharField(max_length=10)),
                ('CREATED', models.DateField()),
                ('UPDATED', models.DateField()),
                ('ALLERGY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.allergy')),
                ('EC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.emergencyContact')),
            ],
        ),
        migrations.CreateModel(
            name='pastOperations',
            fields=[
                ('SURGERY_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('OPERATION', models.TextField(max_length=255)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.main')),
            ],
        ),
        migrations.CreateModel(
            name='pastVisits',
            fields=[
                ('VISIT_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('VISIT', models.TextField(max_length=255)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.main')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('PRESCRIPTION_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PRESCRIPTION', models.TextField(max_length=255)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.main')),
            ],
        ),
        migrations.CreateModel(
            name='primaryDoctor',
            fields=[
                ('PRIMARY_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('F_NAME', models.CharField(max_length=20)),
                ('L_NAME', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='main',
            name='PRESCRIPTION_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.prescription'),
        ),
        migrations.AddField(
            model_name='main',
            name='PRIMARY_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.primaryDoctor'),
        ),
        migrations.AddField(
            model_name='main',
            name='SURGERY_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.pastOperations'),
        ),
        migrations.AddField(
            model_name='main',
            name='VISIT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.pastVisits'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.main'),
        ),
        migrations.AddField(
            model_name='doctornotes',
            name='PRESCRIPTION_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.prescription'),
        ),
        migrations.AddField(
            model_name='doctornotes',
            name='SURGERY_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.pastOperations'),
        ),
        migrations.AddField(
            model_name='doctornotes',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.main'),
        ),
        migrations.AddField(
            model_name='doctornotes',
            name='VISIT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.pastVisits'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.main'),
        ),
    ]
