# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctorNotes',
            new_name='doctorNote',
        ),
        migrations.RenameModel(
            old_name='pastOperations',
            new_name='pastOperation',
        ),
        migrations.RenameModel(
            old_name='pastVisits',
            new_name='pastVisit',
        ),
    ]
