# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20160629_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=b'', max_length=255, unique=True),
        ),
    ]
