# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20160719_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(default=b'', max_length=255, unique=True),
        ),
    ]
